# Generated by Django 3.0.3 on 2020-02-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shijing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=32)),
                ('chapter', models.CharField(default='', max_length=32)),
                ('section', models.CharField(default='', max_length=32)),
                ('content', models.TextField(default='', max_length=8000)),
            ],
        ),
    ]
