# Generated by Django 3.0.3 on 2020-02-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_id', models.IntegerField(default=0)),
                ('author', models.CharField(default='', max_length=32)),
                ('paragraphs', models.TextField(default='', max_length=8000)),
                ('rhythmic', models.CharField(default='', max_length=32)),
                ('tags', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
