# Generated by Django 3.0.3 on 2020-02-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0002_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ci',
            name='tags',
            field=models.CharField(default='', max_length=200),
        ),
    ]
